### ISSUE TITLE
Handling expression of array.

### ISSUE THREAD

**Issue by ANtlord** [Hackerpilot/dsymbol#14]
Hello! 

During fixing [this issue](https://github.com/Hackerpilot/DCD/issues/344) I've met that case considering  [here](https://github.com/Hackerpilot/dsymbol/blob/master/src/dsymbol/conversion/first.d#L1129) an array expression doesn't exist. Correct me if I'm wrong, please. Symbols are built based on data from breadcrumps from type lookups. The application determines explicitly defined identifiers and identifiers defined by `auto` in [this method](https://github.com/Hackerpilot/dsymbol/blob/master/src/dsymbol/conversion/first.d#L198). If it is defined explicitly than information about type filled [here](https://github.com/Hackerpilot/dsymbol/blob/master/src/dsymbol/conversion/first.d#L906). If it is defined by `auto` (implicitly) than application gets information about type from [here](https://github.com/Hackerpilot/dsymbol/blob/master/src/dsymbol/conversion/first.d#L882) and inserts information [here](https://github.com/Hackerpilot/dsymbol/blob/master/src/dsymbol/conversion/first.d#L1129). I'm sure about this and I can show. Take a look at [this](https://gist.github.com/ANtlord/4c8bea27c713ef866c3ebec19a67c70b).

In method that inserts information in breadcrumps I don't see case for an array. But when identifier defined explicitly symbol is added [in this place](https://github.com/Hackerpilot/dsymbol/blob/master/src/dsymbol/conversion/first.d#L936). I suppose that same symbol should be added to breadcrumps to fix completion for implcitly defined arrays.

Also I played with breadcrumps. I've just overloaded method `populateInitializer` for type `Initializer`, removed visiting of visitor and I've inserted symbols `*int` and `*arr*` in breadcrumps manully. It has no effect. @Hackerpilot can you clarify what should happen directly for addition information of a type of implicitly defined identifier? It could be great if you write simple code.  And one more question. Why is asterisk used for symbols for implicitly defined variables? For example: for explicitly defined variable `int`, for implicitly `*int`.

Sorry if my english is not clear.

**Comment by ANtlord** [comment]
Is array determined by `auto` handled in next [method](https://github.com/Hackerpilot/dsymbol/blob/master/src/dsymbol/conversion/first.d#L1189)?

**Comment by BBasile** [comment]
In second.d, in `void resolveTypeFromInitializer`, log the symbol:

```d
                if (i == 0)
		{
			currentSymbol = moduleScope.getFirstSymbolByNameAndCursor(
				symbolNameToTypeName(crumb), symbol.location);
			if (currentSymbol is null)
				return;
                        else writeln("name: ", currentSymbol.name)
		}
```

Then for

```d
auto a = [1];
a.
```

dcd-server outputs directly `int` and I get completion item for an int, not for an array.
If I add a second element to the array then `a.` doesn't give any completion at all.

Based on your second comment, I added this override in first.d:

```d
    override void visit(const ArrayInitializer ai)
    {
        lookup.breadcrumbs.insert(ARRAY_SYMBOL_NAME);
        ai.accept(this);
        import std.stdio;
        writeln(__PRETTY_FUNCTION__);
    }	
```

because actually ` override void visit(const IndexExpression)` is **never** visited.

**Comment by BBasile** [comment]
To be more clear, [this branch](https://github.com/Hackerpilot/dsymbol/blob/master/src/dsymbol/conversion/second.d#L446) is never entered. It looks like it's because the AST visitor in first.d doesn't set `lookup.breadcrumbs.insert(ARRAY_SYMBOL_NAME);` at all.

**Comment by ANtlord** [comment]
@BBasile yes, I've found it too. And it happens beacuse related node doesn't have IndexExpression. This branch isn't involved during expression `auto myarr = [0, 1]`. And I can't understand why. Symbol `[` just skipped.

**Comment by BBasile** [comment]
> beacuse related node doesn't have IndexExpression

No, what I tried to explain is that there's no IndexExpression and that's normal.

The AST for `auto a = [1,2];` is (BTW thank you dscanner for this very useful feature !)

```xml
<autoDeclarationPart>
<item>
<name line="7">a</name>
<initializer>
<nonVoidInitializer>
<arrayInitializer>
<arrayMemberInitialization>
<nonVoidInitializer>
<unaryExpression>
<primaryExpression>
<intLiteral>1</intLiteral>
</primaryExpression>
</unaryExpression>
</nonVoidInitializer>
</arrayMemberInitialization>
<arrayMemberInitialization>
<nonVoidInitializer>
<unaryExpression>
<primaryExpression>
<intLiteral>2</intLiteral>
</primaryExpression>
</unaryExpression>
</nonVoidInitializer>
</arrayMemberInitialization>
</arrayInitializer>
</nonVoidInitializer>
</initializer>
</item>
</autoDeclarationPart>
```

In this case it's clear that no IndexExpression needs to be visited. I means grammatically this is something else. The type should be determined from the data grabbed in `override void visit(const ArrayInitializer ai)`.

**Comment by BBasile** [comment]
To be clear, I really think that's the problem is not in the parser. The problem is that the right thing is not visited. In a variable declaration there's no IndexExpression, thus expecting the override to be visited is a nonsense.

**Comment by ANtlord** [comment]
Hm, I seems it's my fault. What about IndexExpression for `auto myarr = [0, 1]; myarr[0];`?

**Comment by BBasile** [comment]
Sorry there's been a misunderstanding, we don't talk about the same thing. I was speaking about what happens when I type`auto a = [0, 1]; a.` (completion for the array), you were speaking about `myarr[0].` (completion for an array element). So in your case it's clear that you need `IndexExpression` to be visited at a time or another.

The thing is that the array itself is not handled correctly. Depending on if you declare 1 or 2 elements the completion for the array will work or not (if 1 element is declared ok, if 2 nope) and when it works, `.length` and `.ptr` are not in the list.

**Comment by ANtlord** [comment]
> and when it works, .length and .ptr are not in the list

Probably they don't exists because suggested elements are for int.

**Comment by ANtlord** [comment]
> Sorry there's been a misunderstanding, we don't talk about the same thing. I was speaking about what happens when I typeauto a = [0, 1]; a. (completion for the array), you were speaking about auto a = [0, 1]; a[0]. (completion for an array element). So in your case it's clear that you need IndexExpression to be visited at a time or another.

I think that root of both issues is only one.

**Comment by ANtlord** [comment]
Removing of this [code](https://github.com/Hackerpilot/dsymbol/blob/master/src/dsymbol/conversion/second.d#L496)
```d
			typeSwap(currentSymbol);
			if (currentSymbol is null )
				return;
			currentSymbol = currentSymbol.getFirstPartNamed(crumb);
```
allows to get completions for array defined `auto a = [0, 1]; a.`. But it doesn't allow to get completions of array element `auto a = [0, 1]; a[0].`

**Comment by ANtlord** [comment]
I've compared algorigthm using `string` variable and array. Both of them was defined using `auto`. String variable goes through loop once where array goes through twice, and it gets double `typeSwap`.

**Comment by BBasile** [comment]
@ANtlord I'm gonna give a try today. I don't know if you found a good methodology to work on the issue but I had the idea to use a DUB script. It will be easier than using DCD.

```d
/+ dub.sdl:
   name "dub_script"
   dependency "dsymbol" version="~>0.2.0"
+/
module dub_script;

import
    std.stdio, std.experimental.allocator;
import
    dparse.lexer, dparse.parser, dparse.rollback_allocator, dparse.ast;
import
    dsymbol.conversion.first, dsymbol.conversion.second, dsymbol.semantic,
    dsymbol.symbol, dsymbol.scope_, dsymbol.conversion, dsymbol.modulecache;

enum code = q{module test; void foo() {auto intArr = [0,1], intArray.}};

void main(string[] args)
{
    LexerConfig config;
    RollbackAllocator rba;
    StringCache cache = StringCache(StringCache.defaultBucketCount);
    const(Token)[] toks = getTokensForParser(cast(ubyte[]) code, config, &cache);
    ModuleCache mcache = ModuleCache(theAllocator);
    ScopeSymbolPair pair = generateAutocompleteTrees(toks, theAllocator, &rba, 39, mcache);
}
```

Then try and trial in the DSymbol source (as fetched by DUB for this script). With the hope it will help.

**Comment by BBasile** [comment]
Using the above test script I've managed to get the same results for `auto intArr = [1,2]` and `int[] b = [1,2]`. Actually solving `auto` array IS NOT IMPLEMENTED AT ALL !!!

Not yet tested in DCD, b/c there's also assoc array to add:
https://github.com/BBasile/dsymbol/commit/25edb9ba5a6ed0092f43be21ca679d760e4efb66

I've copied the processing fone in `resolveTypeFromType` (in second.d).

**Comment by BBasile** [comment]
Mitigation: The changes fixe only the completion for the array itself. No completion for the elements. Their type is still unresolved.

**Comment by BBasile** [comment]
Good new, it's fixed !

![fix_dsymbol_14](https://cloud.githubusercontent.com/assets/16154339/24075456/4ebba7b0-0c1c-11e7-92d7-0ac078f8acb1.png)

Gonna make a PR ASAP.
