### ISSUE TITLE
wrong version into meson build file

### ISSUE THREAD

**Issue by bioinfornatics** [Hackerpilot/dsymbol#184]
Dear the [meson build file](https://github.com/dlang-community/dsymbol/blob/master/meson.build#L4) have to be updated to match the same tag.
Currently it is 0.14.1 while the file contains 0.4.8

maybe you would have to add a unit test to check automatically

**Comment by WebFreak001** [comment]
this project is no longer active, it has been merged into DCD. You might want to open an issue there instead.
