### ISSUE TITLE
src/dsymbol/conversion/first.d(1029): Assertion failure

### ISSUE THREAD

**Issue by tsbockman** [Hackerpilot/dsymbol#9]
A bug in dsymbol is causing the Travis-CI build to fail with [one of my Phobos pull requests](https://github.com/dlang/phobos/pull/4336):
    https://travis-ci.org/dlang/phobos/builds/131307306

**Comment by Hackerpilot** [comment]
Reduced test case:
```d
private
{
	template S(T)
	{
	public:
		int b;
	}
}
```

**Comment by tsbockman** [comment]
> Reduced test case:

Thanks. Now that I know which part dsymbol is choking on, I was able to simply tweak my syntax a bit to get my PR passing again.
